/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppBudgetRouteImport } from './routes/_app/budget'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppSchedulesRouteImport } from './routes/_app/schedules'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWealthRouteImport } from './routes/_app/wealth'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsCategoriesRouteImport } from './routes/_app/settings/categories'
import { Route as AppSettingsDataRouteImport } from './routes/_app/settings/data'
import { Route as AppSettingsPayeesRouteImport } from './routes/_app/settings/payees'
import { Route as AppSettingsRulesRouteImport } from './routes/_app/settings/rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulesRoute = AppSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWealthRoute = AppWealthRouteImport.update({
  id: '/wealth',
  path: '/wealth',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCategoriesRoute = AppSettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDataRoute = AppSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPayeesRoute = AppSettingsPayeesRouteImport.update({
  id: '/payees',
  path: '/payees',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRulesRoute = AppSettingsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/forecast': typeof AppForecastRoute
  '/insights': typeof AppInsightsRoute
  '/more': typeof AppMoreRoute
  '/schedules': typeof AppSchedulesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/wealth': typeof AppWealthRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/data': typeof AppSettingsDataRoute
  '/settings/payees': typeof AppSettingsPayeesRoute
  '/settings/rules': typeof AppSettingsRulesRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/forecast': typeof AppForecastRoute
  '/insights': typeof AppInsightsRoute
  '/more': typeof AppMoreRoute
  '/schedules': typeof AppSchedulesRoute
  '/wealth': typeof AppWealthRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/data': typeof AppSettingsDataRoute
  '/settings/payees': typeof AppSettingsPayeesRoute
  '/settings/rules': typeof AppSettingsRulesRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/schedules': typeof AppSchedulesRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/wealth': typeof AppWealthRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/settings/categories': typeof AppSettingsCategoriesRoute
  '/_app/settings/data': typeof AppSettingsDataRoute
  '/_app/settings/payees': typeof AppSettingsPayeesRoute
  '/_app/settings/rules': typeof AppSettingsRulesRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/budget'
    | '/dashboard'
    | '/forecast'
    | '/insights'
    | '/more'
    | '/schedules'
    | '/settings'
    | '/wealth'
    | '/accounts/$accountId'
    | '/settings/categories'
    | '/settings/data'
    | '/settings/payees'
    | '/settings/rules'
    | '/accounts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/budget'
    | '/dashboard'
    | '/forecast'
    | '/insights'
    | '/more'
    | '/schedules'
    | '/wealth'
    | '/accounts/$accountId'
    | '/settings/categories'
    | '/settings/data'
    | '/settings/payees'
    | '/settings/rules'
    | '/accounts'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/budget'
    | '/_app/dashboard'
    | '/_app/forecast'
    | '/_app/insights'
    | '/_app/more'
    | '/_app/schedules'
    | '/_app/settings'
    | '/_app/wealth'
    | '/_app/accounts/$accountId'
    | '/_app/settings/categories'
    | '/_app/settings/data'
    | '/_app/settings/payees'
    | '/_app/settings/rules'
    | '/_app/accounts/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedules': {
      id: '/_app/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AppSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wealth': {
      id: '/_app/wealth'
      path: '/wealth'
      fullPath: '/wealth'
      preLoaderRoute: typeof AppWealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/categories': {
      id: '/_app/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AppSettingsCategoriesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/data': {
      id: '/_app/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AppSettingsDataRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/payees': {
      id: '/_app/settings/payees'
      path: '/payees'
      fullPath: '/settings/payees'
      preLoaderRoute: typeof AppSettingsPayeesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/rules': {
      id: '/_app/settings/rules'
      path: '/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof AppSettingsRulesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsCategoriesRoute: typeof AppSettingsCategoriesRoute
  AppSettingsDataRoute: typeof AppSettingsDataRoute
  AppSettingsPayeesRoute: typeof AppSettingsPayeesRoute
  AppSettingsRulesRoute: typeof AppSettingsRulesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsCategoriesRoute: AppSettingsCategoriesRoute,
  AppSettingsDataRoute: AppSettingsDataRoute,
  AppSettingsPayeesRoute: AppSettingsPayeesRoute,
  AppSettingsRulesRoute: AppSettingsRulesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppForecastRoute: typeof AppForecastRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMoreRoute: typeof AppMoreRoute
  AppSchedulesRoute: typeof AppSchedulesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWealthRoute: typeof AppWealthRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppForecastRoute: AppForecastRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMoreRoute: AppMoreRoute,
  AppSchedulesRoute: AppSchedulesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWealthRoute: AppWealthRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
